/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNotifications: typeof import('./components/feedback/AppNotifications.vue')['default']
    AppShell: typeof import('./components/layout/AppShell.vue')['default']
    ClientTable: typeof import('./components/ClientTable.vue')['default']
    DashboardSummaryCards: typeof import('./components/dashboard/DashboardSummaryCards.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LegacyClientsPanel: typeof import('./components/migration/LegacyClientsPanel.vue')['default']
    LegacyClientsTable: typeof import('./components/migration/LegacyClientsTable.vue')['default']
    MigratedClientsPanel: typeof import('./components/migration/MigratedClientsPanel.vue')['default']
    MigratedClientsTable: typeof import('./components/migration/MigratedClientsTable.vue')['default']
    MigrationSnackbar: typeof import('./components/MigrationSnackbar.vue')['default']
    MigrationToolbar: typeof import('./components/MigrationToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
